/**
 * PDF Branding Utilities for JobSight
 *
 * This module provides centralized branding for all PDF documents generated by JobSight.
 * - Adds GC (General Contractor) logo and company information at the top of documents
 * - Adds "Powered by JobSightApp.com" footer at the bottom of every page
 */

import type jsPDF from 'jspdf';
import { supabase } from '@/lib/supabase';

// =====================================================
// CONSTANTS
// =====================================================

export const JOBSIGHT_BRANDING = {
  appName: 'JobSight',
  appUrl: 'JobSightApp.com',
  footerText: 'Powered by JobSightApp.com',
  tagline: 'Construction Field Management',
} as const;

const PAGE_WIDTH = 210; // A4 width in mm
const PAGE_HEIGHT = 297; // A4 height in mm
const MARGIN = 15;
const CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN;

const COLORS = {
  primary: [41, 128, 185] as [number, number, number],
  secondary: [52, 73, 94] as [number, number, number],
  text: [44, 62, 80] as [number, number, number],
  lightGray: [189, 195, 199] as [number, number, number],
} as const;

// =====================================================
// TYPES
// =====================================================

export interface CompanyInfo {
  name: string;
  address?: string;
  phone?: string;
  email?: string;
  website?: string;
  logoUrl?: string;
  logoBase64?: string; // Base64 encoded logo image
}

export interface BrandingOptions {
  gcCompany: CompanyInfo;
  documentTitle: string;
  documentType: string; // e.g., "DAILY REPORT", "RFI", "CHANGE ORDER"
  includeFooter?: boolean; // Default: true
  includeHeader?: boolean; // Default: true
}

// =====================================================
// HEADER FUNCTIONS
// =====================================================

/**
 * Add GC company logo and info at the top of the document
 * Returns the Y position where the main content should start
 */
export async function addDocumentHeader(
  doc: jsPDF,
  options: BrandingOptions
): Promise<number> {
  if (options.includeHeader === false) {
    return MARGIN;
  }

  let yPos = MARGIN;
  const { gcCompany, documentTitle, documentType } = options;

  // Add GC Logo (if provided)
  if (gcCompany.logoBase64) {
    try {
      // Determine image format from base64 string
      const format = getImageFormat(gcCompany.logoBase64);
      doc.addImage(gcCompany.logoBase64, format, MARGIN, yPos, 40, 15);
    } catch (error) {
      console.warn('Failed to add company logo:', error);
    }
  }

  // Company info on the right side
  const rightX = PAGE_WIDTH - MARGIN;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.text);
  doc.text(gcCompany.name, rightX, yPos + 4, { align: 'right' });

  yPos += 6;

  // Company contact details
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.secondary);

  if (gcCompany.address) {
    doc.text(gcCompany.address, rightX, yPos, { align: 'right' });
    yPos += 4;
  }

  if (gcCompany.phone) {
    doc.text(`Tel: ${gcCompany.phone}`, rightX, yPos, { align: 'right' });
    yPos += 4;
  }

  if (gcCompany.email) {
    doc.text(gcCompany.email, rightX, yPos, { align: 'right' });
    yPos += 4;
  }

  // Reset yPos to account for logo height if logo was added
  if (gcCompany.logoBase64) {
    yPos = Math.max(yPos, MARGIN + 18);
  }

  // Document type banner
  doc.setFillColor(...COLORS.primary);
  doc.rect(MARGIN, yPos, CONTENT_WIDTH, 12, 'F');

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text(documentType, PAGE_WIDTH / 2, yPos + 8.5, { align: 'center' });

  yPos += 15;

  // Document title (if different from type)
  if (documentTitle && documentTitle !== documentType) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.text);
    doc.text(documentTitle, MARGIN, yPos);
    yPos += 8;
  }

  // Separator line
  doc.setDrawColor(...COLORS.lightGray);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, yPos, PAGE_WIDTH - MARGIN, yPos);

  return yPos + 8;
}

/**
 * Simplified header without logo (for subsequent pages)
 */
export function addSimplifiedHeader(
  doc: jsPDF,
  documentType: string,
  pageNumber: number
): number {
  let yPos = MARGIN;

  // Document type (smaller)
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.secondary);
  doc.text(documentType, MARGIN, yPos);

  // Page number
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Page ${pageNumber}`, PAGE_WIDTH - MARGIN, yPos, { align: 'right' });

  yPos += 6;

  // Separator line
  doc.setDrawColor(...COLORS.lightGray);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, yPos, PAGE_WIDTH - MARGIN, yPos);

  return yPos + 6;
}

// =====================================================
// FOOTER FUNCTIONS
// =====================================================

/**
 * Add "Powered by JobSightApp.com" footer to the bottom of the page
 */
export function addDocumentFooter(
  doc: jsPDF,
  pageNumber: number,
  totalPages?: number
): void {
  const footerY = PAGE_HEIGHT - MARGIN;

  // Separator line
  doc.setDrawColor(...COLORS.lightGray);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, footerY - 8, PAGE_WIDTH - MARGIN, footerY - 8);

  // Page number (left)
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.secondary);
  const pageText = totalPages ? `Page ${pageNumber} of ${totalPages}` : `Page ${pageNumber}`;
  doc.text(pageText, MARGIN, footerY - 3);

  // Generated date (center)
  const generatedDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
  doc.text(`Generated: ${generatedDate}`, PAGE_WIDTH / 2, footerY - 3, { align: 'center' });

  // JobSight branding (right)
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.primary);
  doc.text(JOBSIGHT_BRANDING.footerText, PAGE_WIDTH - MARGIN, footerY - 3, { align: 'right' });
}

/**
 * Add footers to all pages in the document
 * Call this after all content has been added
 */
export function addFootersToAllPages(doc: jsPDF, totalPages?: number): void {
  const pageCount = totalPages || doc.getNumberOfPages();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    addDocumentFooter(doc, i, pageCount);
  }
}

// =====================================================
// UTILITY FUNCTIONS
// =====================================================

/**
 * Determine image format from base64 string
 */
function getImageFormat(base64: string): 'PNG' | 'JPEG' | 'JPG' {
  if (base64.includes('data:image/png')) {
    return 'PNG';
  }
  if (base64.includes('data:image/jpeg') || base64.includes('data:image/jpg')) {
    return 'JPEG';
  }
  // Default to PNG
  return 'PNG';
}

/**
 * Load company logo from URL and convert to base64
 */
export async function loadCompanyLogo(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';

    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;

      const ctx = canvas.getContext('2d');
      if (!ctx) {
        reject(new Error('Failed to get canvas context'));
        return;
      }

      ctx.drawImage(img, 0, 0);
      const base64 = canvas.toDataURL('image/png');
      resolve(base64);
    };

    img.onerror = () => {
      reject(new Error('Failed to load image'));
    };

    img.src = url;
  });
}

/**
 * Helper to get company info from project/database
 * Fetches company information for PDF branding from Supabase
 */
export async function getCompanyInfo(projectId: string): Promise<CompanyInfo> {
  try {
    // Get project to find company_id
    const { data: project, error: projectError } = await supabase
      .from('projects')
      .select('company_id')
      .eq('id', projectId)
      .single();

    if (projectError || !project) {
      console.warn('Failed to fetch project:', projectError);
      return getDefaultCompanyInfo();
    }

    // Get company data
    const { data: company, error: companyError } = await supabase
      .from('companies')
      .select('name, email, phone, address, city, state, zip, logo_url')
      .eq('id', project.company_id)
      .single();

    if (companyError || !company) {
      console.warn('Failed to fetch company:', companyError);
      return getDefaultCompanyInfo();
    }

    // Build address string from components
    const addressParts = [
      company.address,
      company.city && company.state ? `${company.city}, ${company.state}` : company.city || company.state,
      company.zip
    ].filter(Boolean);
    const address = addressParts.length > 0 ? addressParts.join(', ') : undefined;

    // Load logo if available
    let logoBase64: string | undefined;
    if (company.logo_url) {
      try {
        logoBase64 = await loadCompanyLogo(company.logo_url);
      } catch (error) {
        console.warn('Failed to load company logo:', error);
      }
    }

    return {
      name: company.name,
      address,
      phone: company.phone || undefined,
      email: company.email || undefined,
      website: undefined, // Not in database schema
      logoBase64,
    };
  } catch (error) {
    console.error('Error fetching company info:', error);
    return getDefaultCompanyInfo();
  }
}

/**
 * Returns default company info when database fetch fails
 */
function getDefaultCompanyInfo(): CompanyInfo {
  return {
    name: 'General Contractor',
  };
}

// =====================================================
// USAGE EXAMPLE
// =====================================================

/**
 * Example usage in a PDF export function:
 *
 * ```typescript
 * import jsPDF from 'jspdf';
 * import {
 *   addDocumentHeader,
 *   addFootersToAllPages,
 *   getCompanyInfo,
 *   type BrandingOptions
 * } from '@/lib/utils/pdfBranding';
 *
 * export async function generateMyPDF(projectId: string) {
 *   const doc = new jsPDF();
 *   const gcCompany = await getCompanyInfo(projectId);
 *
 *   // Add header with GC branding
 *   const startY = await addDocumentHeader(doc, {
 *     gcCompany,
 *     documentTitle: 'Daily Report - January 15, 2024',
 *     documentType: 'DAILY REPORT',
 *   });
 *
 *   // Add your content starting at startY
 *   // ... your content here ...
 *
 *   // Add footers to all pages at the end
 *   addFootersToAllPages(doc);
 *
 *   return doc.output('blob');
 * }
 * ```
 */
