/**
 * Test Data Factories
 * Central export for all mock data factories
 */

// User factory
export {
  createMockUser,
  createMockAuthUser,
  createMockSession,
  createMockSuperintendent,
  createMockAdmin,
  createMockProjectManager,
  createMockForeman,
  createMockViewer,
  createMockUsers,
  createMockUserWithAuth,
  TEST_USERS,
  type MockUser,
  type MockAuthUser,
  type MockSession,
  type UserRole,
  type UserFactoryOptions,
  type AuthUserFactoryOptions,
  type SessionFactoryOptions,
} from './user.factory';

// Project factory
export {
  createMockProject,
  createMockProjectAssignment,
  createMockActiveProject,
  createMockCompletedProject,
  createMockOnHoldProject,
  createMockPreConstructionProject,
  createMockProjects,
  createMockProjectWithAssignments,
  TEST_PROJECTS,
  type MockProject,
  type MockProjectAssignment,
  type ProjectStatus,
  type ProjectType,
  type ProjectPhase,
  type ProjectFactoryOptions,
  type ProjectAssignmentFactoryOptions,
} from './project.factory';

// Daily Report factory
export {
  createMockDailyReport,
  createMockWorkforceEntry,
  createMockEquipmentEntry,
  createMockDelayEntry,
  createMockSafetyIncident,
  createMockInspectionEntry,
  createMockPhotoEntry,
  createMockDeliveryEntry,
  createMockDraftReport,
  createMockSubmittedReport,
  createMockApprovedReport,
  createMockDailyReports,
  createMockDailyReportWithEntries,
  TEST_DAILY_REPORTS,
  type MockDailyReport,
  type MockWorkforceEntry,
  type MockEquipmentEntry,
  type MockDelayEntry,
  type MockSafetyIncident,
  type MockInspectionEntry,
  type MockPhotoEntry,
  type MockDeliveryEntry,
  type DailyReportFactoryOptions,
  type WorkforceEntryFactoryOptions,
  type DelayEntryFactoryOptions,
  type SafetyIncidentFactoryOptions,
} from './dailyReport.factory';

// Document factory
export {
  createMockDocument,
  createMockDocumentFolder,
  createMockDocumentVersion,
  createMockDrawing,
  createMockDrawingSet,
  createMockApprovedDocument,
  createMockRejectedDocument,
  createMockDocuments,
  createMockDrawings,
  createMockFolderWithDocuments,
  createMockDrawingSetWithDrawings,
  TEST_DOCUMENTS,
  TEST_DRAWINGS,
  type MockDocument,
  type MockDocumentFolder,
  type MockDocumentVersion,
  type MockDrawing,
  type MockDrawingSet,
  type DocumentStatus,
  type DocumentType,
  type DocumentCategory,
  type DocumentFactoryOptions,
  type DrawingFactoryOptions,
  type FolderFactoryOptions,
} from './document.factory';

// DocuSign factory
export {
  createMockDSConnection,
  createMockDSEnvelope,
  createMockDSRecipient,
  createMockDSEnvelopeDocument,
  createMockDSEnvelopeEvent,
  createMockDSConnectionStatus,
  createMockDSEnvelopeStats,
  createMockDSOAuthTokens,
  createMockDSUserInfo,
  createMockDSAccountInfo,
  createMockActiveDSConnection,
  createMockInactiveDSConnection,
  createMockDemoDSConnection,
  createMockErrorDSConnection,
  createMockCompletedDSEnvelope,
  createMockPendingDSEnvelope,
  createMockDeclinedDSEnvelope,
  createMockDSEnvelopes,
  createMockDSEnvelopeWithDetails,
  TEST_DOCUSIGN,
  type DSConnectionFactoryOptions,
  type DSEnvelopeFactoryOptions,
  type DSRecipientFactoryOptions,
  type DSEnvelopeDocumentFactoryOptions,
} from './docusign.factory';

// Action Item factory
export {
  createMockActionItem,
  createMockActionItemWithContext,
  createMockOpenActionItem,
  createMockOverdueActionItem,
  createMockDueSoonActionItem,
  createMockInProgressActionItem,
  createMockCompletedActionItem,
  createMockEscalatedActionItem,
  createMockChronicActionItem,
  createMockActionItems,
  createMockActionItemProjectSummary,
  createMockActionItemsByAssignee,
  createMockActionItemsByAssignees,
  TEST_ACTION_ITEMS,
  type MockActionItem,
  type MockActionItemWithContext,
  type MockActionItemProjectSummary,
  type MockActionItemsByAssignee,
  type ActionItemFactoryOptions,
  type ActionItemWithContextFactoryOptions,
} from './actionItem.factory';

// Sync Conflict factory
export {
  createMockSyncConflict,
  createMockLocalNewerConflict,
  createMockServerNewerConflict,
  createMockFieldLevelConflict,
  createMockSyncConflicts,
  createMockResolvedConflict,
  TEST_CONFLICTS,
  type MockSyncConflict,
  type SyncConflictFactoryOptions,
} from './syncConflict.factory';

// Pending Sync Item factory
export {
  createMockPendingSyncItem,
  createMockCreateSyncItem,
  createMockUpdateSyncItem,
  createMockDeleteSyncItem,
  createMockSyncingItem,
  createMockFailedSyncItem,
  createMockMaxRetriesSyncItem,
  createMockPendingSyncItems,
  createMockMixedSyncBatch,
  createMockLargeSyncQueue,
  TEST_SYNC_ITEMS,
  type MockPendingSyncItem,
  type PendingSyncItemFactoryOptions,
} from './pendingSyncItem.factory';

// Submittal factory
export {
  createMockWorkflowType,
  createMockSubmittal,
  createMockDraftSubmittal,
  createMockSubmittedSubmittal,
  createMockApprovedSubmittal,
  createMockRejectedSubmittal,
  createMockUnderReviewSubmittal,
  createMockSubmittals,
  createMockSubmittalProcurement,
  createMockPendingProcurement,
  createMockOrderedProcurement,
  createMockDeliveredProcurement,
  createMockProcurements,
  createMockSubmittalWithProcurement,
  TEST_SUBMITTALS,
  TEST_WORKFLOW_TYPE,
  TEST_PROCUREMENT,
  type MockWorkflowItem,
  type MockWorkflowType,
  type MockSubmittalProcurement,
  type SubmittalStatus,
  type ProcurementStatus,
  type WorkflowItemFactoryOptions,
  type WorkflowTypeFactoryOptions as SubmittalWorkflowTypeFactoryOptions,
  type SubmittalProcurementFactoryOptions,
} from './submittal.factory';

// RFI factory
export {
  createMockRFI,
  createMockPendingRFI,
  createMockSubmittedRFI,
  createMockApprovedRFI,
  createMockRejectedRFI,
  createMockClosedRFI,
  createMockHighPriorityRFI,
  createMockOverdueRFI,
  createMockUnassignedRFI,
  createMockRFIWithoutDueDate,
  createMockRFIs,
  createMockRFIComment,
  createMockRFIComments,
  createMockRFIHistory,
  createMockStatusChangeHistory,
  createMockRFIHistoryEntries,
  createMockRFIWorkflowType,
  createMockRFIWithContext,
  TEST_RFIS,
  type RFIFactoryOptions,
  type RFICommentFactoryOptions,
  type RFIHistoryFactoryOptions,
  type WorkflowTypeFactoryOptions as RFIWorkflowTypeFactoryOptions,
} from './rfi.factory';

// Dashboard factory
export {
  createMockDashboardStats,
  createEmptyDashboardStats,
  createCriticalDashboardStats,
  createMockDashboardActionItem,
  createOverdueActionItem,
  createUrgentActionItem,
  createMockDashboardActionItems,
  createMixedActionItems,
  createMockProjectStats,
  createEmptyProjectStats,
  createMockCountResponse,
  createMockDataResponse,
  createMockErrorResponse,
  TEST_DASHBOARD_STATS,
  TEST_ACTION_ITEMS_DASHBOARD,
  TEST_PROJECT_STATS,
  type DashboardStatsFactoryOptions,
  type ActionItemFactoryOptions as DashboardActionItemFactoryOptions,
  type ProjectStatsFactoryOptions,
} from './dashboard.factory';

// Procurement factory
export {
  createMockVendor,
  createMockVendors,
  createInactiveVendor,
  createUnapprovedVendor,
  createMockPurchaseOrder,
  createMockPurchaseOrders,
  createDraftPO,
  createApprovedPO,
  createOrderedPO,
  createCancelledPO,
  createMockPOLineItem,
  createMockPOLineItems,
  createPartiallyReceivedLineItem,
  createReceivedLineItem,
  createMockPOReceipt,
  createMockPOReceipts,
  createDamagedReceipt,
  createMockProcurementStats,
  createEmptyProcurementStats,
  createVendorDTO,
  createUpdateVendorDTO,
  createPurchaseOrderDTO,
  createUpdatePurchaseOrderDTO,
  createLineItemDTO,
  createUpdateLineItemDTO,
  createReceiptDTO,
  createVendorFilters,
  createPurchaseOrderFilters,
  TEST_PROCUREMENT_DATA,
  type VendorFactoryOptions,
  type PurchaseOrderFactoryOptions,
  type POLineItemFactoryOptions,
  type POReceiptFactoryOptions,
  type ProcurementStatsFactoryOptions,
} from './procurement.factory';

// Owner Invoice factory
export {
  createMockOwnerInvoice,
  createDraftInvoice,
  createSentInvoice,
  createOverdueInvoice,
  createPaidInvoice,
  createMockOwnerInvoices,
  createMixedInvoices,
  createMockInvoiceWithDetails,
  createMockLineItem,
  createMockLineItems,
  createMockPayment,
  createMockPayments,
  createMockInvoiceStats,
  createEmptyInvoiceStats,
  createMockAgingItem,
  createMockAgingSummary,
  createMockAgingReport,
  createMockSingleResponse,
  TEST_INVOICES,
  TEST_INVOICE_STATS,
  TEST_AGING_REPORT,
  type OwnerInvoiceFactoryOptions,
  type LineItemFactoryOptions,
  type PaymentFactoryOptions,
  type InvoiceStatsFactoryOptions,
} from './ownerInvoice.factory';
