// File: /src/features/documents/types/drawing-set.ts
// Type definitions for drawing set management features

import type { ChangeRegion } from './markup'

// ============================================================
// SHEET REFERENCES & HYPERLINKS
// ============================================================

/**
 * Reference type for cross-sheet references
 */
export type SheetReferenceType =
  | 'detail'
  | 'section'
  | 'elevation'
  | 'plan'
  | 'schedule'
  | 'general'

/**
 * Represents a hyperlink reference from one drawing sheet to another
 */
export interface SheetReference {
  id: string
  sourceDocumentId: string
  targetDocumentId: string
  sourceLocation: {
    x: number
    y: number
    page: number
  }
  referenceText: string
  referenceType: SheetReferenceType
  createdBy: string
  createdAt: string
  updatedAt?: string
  // Auto-detected or manually created
  isAutoDetected: boolean
  // Confidence level for auto-detected references (0-1)
  confidence?: number
}

/**
 * Parsed drawing reference from text
 */
export interface ParsedDrawingReference {
  fullMatch: string
  drawingNumber: string
  detailNumber?: string
  sheetNumber?: string
  referenceType: SheetReferenceType
}

/**
 * Backlink from a target sheet showing incoming references
 */
export interface SheetBacklink {
  id: string
  sourceDocumentId: string
  sourceDocumentName: string
  sourceDrawingNumber?: string
  referenceText: string
  referenceType: SheetReferenceType
  location: {
    x: number
    y: number
    page: number
  }
}

/**
 * Sheet with hyperlink metadata
 */
export interface SheetWithLinks {
  documentId: string
  documentName: string
  drawingNumber?: string
  outgoingLinks: SheetReference[]
  incomingLinks: SheetBacklink[]
  hasLinks: boolean
}

// ============================================================
// REVISION CLOUDS
// ============================================================

/**
 * Revision marker on a drawing
 */
export interface RevisionCloud {
  id: string
  documentId: string
  versionFrom: number
  versionTo: number
  region: {
    points: Array<{ x: number; y: number }>
    // Bounding box for quick hit testing
    bounds: {
      x: number
      y: number
      width: number
      height: number
    }
  }
  description: string
  revisionNumber: string
  revisionDate: string
  createdBy: string
  createdAt: string
  // Whether this was auto-generated from comparison
  isAutoGenerated: boolean
  // Page number for multi-page documents
  pageNumber: number
  // Optional: Link to RFI or ASI that prompted the revision
  linkedRfiId?: string
  linkedAsiId?: string
  // Color for display
  color: string
  // Whether the cloud should show the revision marker (delta symbol, etc.)
  showMarker: boolean
  markerPosition: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right'
}

/**
 * Revision history entry for a document
 */
export interface RevisionHistoryEntry {
  id: string
  documentId: string
  revisionNumber: string
  revisionDate: string
  description: string
  createdBy: string
  createdByName?: string
  createdAt: string
  clouds: RevisionCloud[]
  // Number of changes detected
  changeCount: number
  // Percentage of drawing that changed
  changePercentage: number
}

/**
 * Options for auto-generating revision clouds
 */
export interface RevisionCloudGenerationOptions {
  // Minimum change region size to create a cloud
  minRegionSize: number
  // Whether to merge nearby regions
  mergeNearbyRegions: boolean
  // Distance threshold for merging (in pixels)
  mergeDistance: number
  // Default color for clouds
  defaultColor: string
  // Whether to show revision markers
  showMarkers: boolean
  // Default marker position
  markerPosition: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right'
}

// ============================================================
// BULK MARKUP APPLICATION
// ============================================================

/**
 * Position adjustment strategy when applying markups to other sheets
 */
export type MarkupPositionStrategy =
  | 'same-position' // Keep exact coordinates
  | 'centered'      // Center on target sheet
  | 'scaled'        // Scale to fit target sheet dimensions
  | 'relative'      // Keep relative position (percentage-based)

/**
 * Selection of markups to apply in bulk
 */
export interface BulkMarkupSelection {
  markupIds: string[]
  sourceDocumentId: string
  sourcePageNumber?: number
}

/**
 * Target sheet for bulk markup application
 */
export interface BulkMarkupTarget {
  documentId: string
  documentName: string
  pageNumber?: number
  // Whether this sheet is selected
  selected: boolean
}

/**
 * Options for bulk markup application
 */
export interface BulkMarkupApplyOptions {
  positionStrategy: MarkupPositionStrategy
  // Whether to create a copy or reference
  createCopy: boolean
  // Whether to preserve original colors
  preserveColors: boolean
  // Optional scale factor for 'scaled' strategy
  scaleFactor?: number
  // Optional offset for 'same-position' strategy
  offset?: { x: number; y: number }
}

/**
 * Result of bulk markup application
 */
export interface BulkMarkupApplyResult {
  success: boolean
  appliedCount: number
  failedCount: number
  errors: Array<{
    targetDocumentId: string
    error: string
  }>
  createdMarkupIds: string[]
}

/**
 * Progress update during bulk operation
 */
export interface BulkOperationProgress {
  current: number
  total: number
  currentTarget?: string
  status: 'pending' | 'in-progress' | 'completed' | 'failed'
  message?: string
}

// ============================================================
// MARKUP MIGRATION
// ============================================================

/**
 * Migration status for a markup
 */
export type MarkupMigrationStatus =
  | 'pending'
  | 'migrated'
  | 'adjusted'
  | 'skipped'
  | 'failed'

/**
 * Markup ready for migration to a new version
 */
export interface MigratableMarkup {
  id: string
  markupType: string
  markupData: Record<string, unknown>
  pageNumber: number
  // Original position
  originalPosition: { x: number; y: number }
  // Suggested new position (if drawing has changed)
  suggestedPosition?: { x: number; y: number }
  // Migration status
  status: MarkupMigrationStatus
  // Whether this markup overlaps with a detected change region
  overlapsChange: boolean
  // Confidence in the suggested position (0-1)
  positionConfidence?: number
}

/**
 * Options for markup migration
 */
export interface MarkupMigrationOptions {
  // Whether to auto-migrate markups that don't overlap changes
  autoMigrateUnchanged: boolean
  // Whether to attempt smart repositioning for changed areas
  smartReposition: boolean
  // Whether to keep a reference to the original markup
  keepOriginalReference: boolean
  // Whether to skip markups that overlap with change regions
  skipOverlapping: boolean
}

/**
 * Result of markup migration
 */
export interface MarkupMigrationResult {
  success: boolean
  migratedCount: number
  skippedCount: number
  failedCount: number
  migratedMarkups: Array<{
    originalId: string
    newId: string
    status: MarkupMigrationStatus
  }>
}

/**
 * New revision detection result
 */
export interface NewRevisionDetection {
  documentId: string
  documentName: string
  newVersion: string
  previousVersion: string
  previousDocumentId: string
  detectedAt: string
  hasMigratableMarkups: boolean
  markupCount: number
}

// ============================================================
// DRAWING COMPARISON ENHANCEMENTS
// ============================================================

/**
 * Comparison view mode
 */
export type ComparisonViewMode =
  | 'side-by-side'
  | 'overlay'
  | 'flicker'
  | 'difference'

/**
 * Flicker mode settings
 */
export interface FlickerSettings {
  // Interval between flickers in milliseconds
  interval: number
  // Whether flicker is currently active
  isActive: boolean
  // Current visible version (1 or 2)
  currentVersion: 1 | 2
}

/**
 * Enhanced overlay settings with more options
 */
export interface EnhancedOverlaySettings {
  // Opacity for older version (0-100)
  opacity1: number
  // Opacity for newer version (0-100)
  opacity2: number
  // CSS blend mode
  blendMode: 'normal' | 'difference' | 'multiply' | 'overlay' | 'screen' | 'darken' | 'lighten'
  // Whether to show change highlights
  showChangeHighlights: boolean
  // Color for change highlights
  changeHighlightColor: string
  // Opacity for change highlights (0-100)
  changeHighlightOpacity: number
  // Whether to tint each version differently
  useTinting: boolean
  // Tint color for older version
  tint1: string
  // Tint color for newer version
  tint2: string
}

/**
 * Synchronized pan/zoom state
 */
export interface SyncedViewState {
  // Current zoom level (percentage)
  zoom: number
  // Pan position
  position: { x: number; y: number }
  // Current page number
  pageNumber: number
  // Whether sync is enabled
  syncEnabled: boolean
}

/**
 * Difference highlighting colors
 */
export interface DifferenceColors {
  added: string
  removed: string
  modified: string
  // Optional opacity override
  opacity?: number
}

/**
 * Full comparison state
 */
export interface DrawingComparisonState {
  viewMode: ComparisonViewMode
  flickerSettings: FlickerSettings
  overlaySettings: EnhancedOverlaySettings
  syncedView: SyncedViewState
  differenceColors: DifferenceColors
  // Selected change region for detail view
  selectedChangeRegion?: ChangeRegion
  // Whether to show change region list
  showChangeList: boolean
}

// ============================================================
// DRAWING SET INDEX
// ============================================================

/**
 * Entry in the drawing set index
 */
export interface DrawingSetEntry {
  documentId: string
  drawingNumber: string
  sheetTitle: string
  discipline: string
  currentRevision: string
  revisionDate: string
  // Number of outgoing hyperlinks
  outgoingLinkCount: number
  // Number of incoming hyperlinks
  incomingLinkCount: number
  // Whether this sheet has markups
  hasMarkups: boolean
  // Number of revision clouds
  revisionCloudCount: number
}

/**
 * Drawing set summary statistics
 */
export interface DrawingSetStats {
  totalSheets: number
  totalRevisionClouds: number
  totalHyperlinks: number
  sheetsWithMarkups: number
  disciplineBreakdown: Record<string, number>
  lastUpdated: string
}
